---

- name: install/update packages
  become: yes
  apt:
    state: latest
    name:
      - smartmontools
      - sqlitebrowser
      - remmina
      - network-manager-openvpn-gnome
      - birdtray
      - dcraw
      - virt-manager
      - gnome-disk-utility
      - ttf-mscorefonts-installer
      - fonts-powerline
      - gnome-calculator
      - gnome-calendar
      - gnome-firmware
      - gnome-genius
      - arandr
      - meld  # Diff app
      - gvfs-backends # Allow Windows network browsing
      - timeshift # OS state snapshoting
      - gvfs-fuse # all Thunar/Gio mounts under /run/user/1000/gvfs
      - cifs-utils # required for Veeam Backup

- name: remove packages
  become: yes
  apt:
    state: absent
    name:
      - docker.io
      - xnbd-client

- name: Install edge snap apps
  become: true
  snap:
    name:
      - libreoffice
      - chromium
      - darktable
      - inkscape
      - signal-desktop
      - spotify
      - skype
      - telegram-desktop
      - xournalpp
    #channel: latest/edge

- name: Install edge snap apps with classic confinement
  become: true
  snap:
    name:
      - slack
      - restic
    channel: latest/edge
    classic: true

- name: Remove snap apps
  become: true
  snap:
    state: absent
    name:
      - zoom-client # problems with links, used vendor's DEB