---

- name: install/update packages
  become: yes
  apt:
    state: latest
    name:
      - libreoffice
      - tlp
      - smartmontools
      - sqlitebrowser
      - remmina
      - network-manager-openvpn-gnome
      - birdtray

- name: remove packages
  become: yes
  apt:
    state: absent
    name:
      - mono-complete
      - docker.io
      - xnbd-client
      - uvcdynctrl # https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1626731
      - virtualbox
      - virtualbox-dkms
      - strawberry

- name: Install edge snap apps
  become: true
  snap:
    name:
      - chromium
      - darktable
      - inkscape
      - restic
      - signal-desktop
      - spotify
      - skype
      - telegram-desktop
      - xournalpp
      - drawio
    channel: latest/edge

- name: Install edge snap apps with classic confinement
  become: true
  snap:
    name:
      - slack
    channel: latest/edge
    classic: true

- name: Remove snap apps
  become: true
  snap:
    state: absent
    name:
      - zoom-client # problems with links, used vendor's DEB