---

- name: allow USB access to dymo printer
  become: true
  blockinfile:
    path: /etc/udev/rules.d/91-dymo-1002.rules
    create: yes
    block: |
      ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="0922", ATTRS{idProduct}=="1002", MODE="0666", ENV{UDISKS_IGNORE}="1"
  notify: Reload udev rules
  tags: print

- name: Install labelle python package
  pip:
    name: labelle

# https://github.com/labelle-org/labelle