---
- name: install/update packages
  become: yes
  apt:
    state: latest
    name:
      - xfce4-goodies
      - papirus-icon-theme
      - arc-theme

- name: get client side decorations in dialogs setting
  shell: xfconf-query -c xsettings -p /Gtk/DialogsUseHeader
  register: client_side_decoration
  changed_when: False

- name: disable client side decorations in dialogs
  shell: xfconf-query -c xsettings -p /Gtk/DialogsUseHeader -s false
  when: "'false' not in client_side_decoration.stdout"