---
# pip3 install ansible
# ansible-galaxy collection install community.general
# ansible-galaxy collection install community.docker

#Xubuntu 22.04
- name: xubuntu t14 local playbook
  hosts: localhost
  connection: local
  become: no
  vars:
    executing_user: "{{ ansible_user_id }}"
  tasks:

    - name: Update package lists
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 86400 #24h
      tags: apps, shell, dev, xfce

    # Common
    - import_tasks: tasks/cmdline-tools.yaml
      tags: shell, apps
    - import_tasks: tasks/fish.yaml
      tags: fish, shell
    - import_tasks: tasks/starship.yaml
      tags: shell
    - import_tasks: tasks/bash.yaml
      tags: shell
    - import_tasks: tasks/asdf.yaml
      tags: dev, shell, asdf
    - import_tasks: tasks/wireguard.yaml
      tags: wg
    - import_tasks: tasks/syncthing.yaml
      tags: syncthing

    # Desktop stuff
    - import_tasks: tasks/desktop/apps.yaml
      tags: apps
    - import_tasks: tasks/desktop/ddcutil.yaml
      tags: hw, desktop, apps
    - import_tasks: tasks/desktop/redshift.yaml
      tags: xfce, desktop, apps
    - import_tasks: tasks/desktop/xfce.yaml
      tags: xfce
    - import_tasks: tasks/desktop/kitty.yaml
      tags: term, kitty
    - import_tasks: tasks/desktop/dymo-pnp.yaml
      tags: print
    - import_tasks: tasks/desktop/wacom.yaml
      tags: wacom
    - import_tasks: tasks/desktop/obs.yaml
      tags: obs, desktop, apps

    # Server stuff
    - import_tasks: tasks/server/qemu.yaml
      tags: qemu

    - import_tasks: tasks/server/docker.yaml
      tags: docker

    # Other this machine specific
    - name: Disable NetworkManager await for a connection at boot
      # sudo systemd-analyze critical-chain to see more services delaying the boot-up
      become: true
      systemd:
        name: NetworkManager-wait-online.service
        enabled: false
      tags: net

    - name: optimize network usage
      become: true
      blockinfile:
        path: /etc/systemd/network/01-tso-and-gso.link
        create: yes
        block: |
          [Match]
          # Set a match condition appropriate for your use case
          Name=*

          [Link]
          TCPSegmentationOffload=false
          GenericSegmentationOffload=false
      tags: net

    # 23.10 https://askubuntu.com/questions/1489925/bluetooth-wont-connect-after-upgrade-to-23-10
    - name: Fix bluetooth audio
      apt:
        name:
          - libspa-0.2-bluetooth

        #  - name: setup nbd kernel module
        #    modprobe:
        #      name: nbd
        #      params: 'nbds_max=1'

        #  - name: create Xorg conf.d directory
        #    file: path=/etc/X11/xorg.conf.d/ state=directory

        #  - name: set tear free screen rendering - fixes scroll tear issue
        #    blockinfile:
        #      path: /etc/X11/xorg.conf.d/20-intel.conf
        #      create: yes
        #      block: |
        #        Section "Device"
        #          Identifier "card0"
        #          Driver "intel"
        #          Option "TearFree" "true"
        #          Option "Backlight"  "intel_backlight"
        #Option  "AccelMethod" "uxa"
      #Option  "TripleBuffer" "true"
    #          BusID       "PCI:0:2:0"
    #        EndSection

  handlers:
    - name: Reload udev rules
      become: true
      command: udevadm control --reload-rules
