---

#Xubuntu 21.04
- name: xubuntu t14 local playbook
  hosts: localhost
  connection: local
  become: no
  vars:
    executing_user: "{{ ansible_user_id }}"
  tasks:

    - name: Update package lists
      become: yes
      apt:
        update_cache: yes

    # Common
    - import_tasks: tasks/fish.yaml
      tags: fish, shell
    - import_tasks: tasks/starship.yaml
      tags: shell
    - import_tasks: tasks/cmdline-tools.yaml
      tags: shell, apps
    - import_tasks: tasks/bash.yaml
      tags: shell
    - import_tasks: tasks/asdf.yaml
      tags: dev

    # Desktop stuff
    - import_tasks: tasks/desktop/apps.yaml
      tags: apps
    - import_tasks: tasks/desktop/ddcutil.yaml
      tags: hw, desktop, apps
    - import_tasks: tasks/desktop/redshift.yaml
      tags: xfce, desktop, apps
    - import_tasks: tasks/desktop/xfce.yaml
      tags: xfce
    - import_tasks: tasks/desktop/joplin.yaml
      tags: apps, joplin
    - import_tasks: tasks/desktop/kitty.yaml
      tags: term, kitty
    - import_tasks: tasks/desktop/fonts.yaml
      tags: xfce, desktop

    # Server stuff
    - import_tasks: tasks/server/qemu.yaml
      tags: qemu

    # Other
    - name: optimize network usage
      become: true
      blockinfile:
        path: /etc/systemd/network/01-tso-and-gso.link
        create: yes
        block: |
          [Match]
          # Set a match condition appropriate for your use case
          Name=*

          [Link]
          TCPSegmentationOffload=false
          GenericSegmentationOffload=false
      tags: net

        #  - name: setup nbd kernel module
        #    modprobe:
        #      name: nbd
        #      params: 'nbds_max=1'

        #  - name: create Xorg conf.d directory
        #    file: path=/etc/X11/xorg.conf.d/ state=directory

        #  - name: set tear free screen rendering - fixes scroll tear issue
        #    blockinfile:
        #      path: /etc/X11/xorg.conf.d/20-intel.conf
        #      create: yes
        #      block: |
        #        Section "Device"
        #          Identifier "card0"
        #          Driver "intel"
        #          Option "TearFree" "true"
        #          Option "Backlight"  "intel_backlight"
        #Option  "AccelMethod" "uxa"
      #Option  "TripleBuffer" "true"
    #          BusID       "PCI:0:2:0"
    #        EndSection

    #Docker
    #  - name: Make docker group for unpriviledged users
    #    tags: docker
    #    group: name=docker

    #  - name: install/update packages
    #    tags: docker
    #    apt: name={{item}} state=latest update_cache=yes
    #    with_items:
    #      - docker.io

    #  - name: Adding user to docker group
    #    tags: docker
    #    user:
    #      name: {{ executing_user }}
    #      groups: docker
    #      append: yes

    #  - name: Run docker service
    #    tags: docker
    #    service: name="docker" state="started"