---

- name: Install ASDF - meta env version manager, node and ruby
  git:
    clone: true
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: ~/.asdf

- name: Configure asdf rc file
  copy:
    src: "home/.asdfrc"
    dest: "~/"
  tags: shell

- name: Default tool versions for asdf
  copy:
    src: ".tool-versions"
    dest: "~/"

- name: Add plugins
  shell:
    cmd: |
      set PRE_CHECK (asdf plugin list)
      cut -d' ' -f1 ~/.tool-versions|xargs -i asdf -v plugin add  {}
      set POST_CHECK (asdf plugin list)
      if test "$PRE_CHECK" != "$POST_CHECK" ; echo "ansible changed!" ; end
    executable: /usr/bin/fish
  register: asdf_install_result
  changed_when: "'ansible changed!' in asdf_install_result.stderr"
  failed_when: "'not found' in asdf_install_result.stdout"

- name: ASDF install
  shell:
    cmd: 'asdf install'
    executable: /usr/bin/fish
  register: asdf_install
  changed_when: "'Installing' in asdf_install.stdout"