---

- name: Install inotify tools
  become: yes
  apt:
    state: latest
    name:
      - inotify-tools

- name: Raise inotify limits
  become: true
  sysctl:
    name: fs.inotify.max_user_watches
    value: 262144
    state: present
