---

- name: Install shell utilities - starship, direnv
  become: true
  snap:
    name:
      - starship
      - direnv
    channel: edge
  tags: shell

- name: Configure starship prompt
  copy:
    src: "config/starship.toml"
    dest: "~/.config/starship.toml"
    backup: yes
  tags: shell

- name: Add permissions to AppArmor profile
  become: true
  lineinfile:
    path: /var/lib/snapd/apparmor/profiles/snap.starship.starship
    insertbefore: '^}'
    line: "{{ item }}"
  loop:
    - "/sys/fs/cgroup/{,**/}cpu.max r,"
    - "/sys/devices/**/power_supply/*/* r,"
  notify: Reload AppArmor profiles