---

- name: Install shell utilities - starship, direnv
  become: true
  snap:
    name:
      - starship
      - direnv
    channel: edge
  tags: shell

- name: Configure starship prompt
  copy:
    src: "config/starship.toml"
    dest: "~/.config/starship.toml"
    backup: yes
  tags: shell
