---

- name: Install wireguard
  become: true
  apt:
    name:
      - wireguard-tools

- name: Allow DNS split horizon with wg-quick expects it
  become: true
  file:
    src: "/usr/bin/resolvectl"
    dest: "/usr/local/bin/resolvconf"
    state: link

# https://ubuntu.com/server/docs/wireguard-vpn-other-tasks

- name: Deploy WireGuard retry script
  become: true
  copy:
    dest: /usr/local/bin/wg-quick-watchdog.sh
    content: |
      #!/bin/bash
      RETRY_INTERVAL=60 # Retry every 60 seconds
      WG_DIR="/etc/wireguard"
      configs=$(find "$WG_DIR" -type f -name "*.conf" -exec basename {} .conf \;)
      while true; do
          all_interfaces_up=true
          for config in $configs; do
              if ip link show dev "$config" > /dev/null 2>&1; then
                  echo "WireGuard interface ${config} is already up."
              else
                  all_interfaces_up=false
                  if wg-quick up "$config"; then
                      echo "WireGuard interface ${config} is now up."
                  else
                      echo "Failed to bring up ${config}. Retrying in ${RETRY_INTERVAL} seconds..."
                  fi
              fi
          done
          if $all_interfaces_up; then
              RETRY_INTERVAL=3600 # 1 hour
          else
              RETRY_INTERVAL=60 # 1 minute
          fi
          echo "Waiting for ${RETRY_INTERVAL} seconds before recheck..."
          sleep $RETRY_INTERVAL
      done
    mode: '0755'

- name: Create systemd service for wg-quick-watchdog
  become: true

  copy:
    dest: /etc/systemd/system/wg-quick-watchdog.service
    content: |
      [Unit]
      Description=Retry WireGuard Configurations
      Wants=network-online.target
      After=network-online.target
      Before=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/wg-quick-watchdog.sh
      Restart=always
      RestartSec=30

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify: Reload systemd

- name: Enable and start wg-quick-watchdog service
  systemd:
    name: wg-quick-watchdog
    enabled: yes
    state: started